### ISSUE TITLE
Magento 2.4.1

### ISSUE THREAD

**Issue by fabiofbra** [webidea24/magento2-module-custom-address-line-labels#1]
Did not work in magento 2.4.1.

- Installation ok. 
- Admin configuration ok. 
- Front-end with/out labels.

![image](https://user-images.githubusercontent.com/16707446/124707056-ac489800-dece-11eb-9aa4-6eb5dbf79f1a.png)

Any advice?

**Comment by rommelfreddy** [comment]
Hello @fabiofbra 
i am so sorry for the late response. 

I can not reproduce the issue, that you got none of the labels. 

I found an issue, that the first label got not displayed. 
This has been fixed in the new release: https://github.com/webidea24/magento2-module-custom-address-line-labels/releases/tag/1.0.1

Please make sure, that there is no CSS which is hiding the labels.
